import './globals.css';
import { Rubik } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import Navbar from './components/navbar';

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Ian Olmstead',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gradient-to-bl from-gray-600 to-gray-300">
      <body className={rubik.className}>
        <div className="p-6">
          <Navbar />
          {children}
          <Analytics />
        </div>
      </body>
    </html>
  )
};
