import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        
      </head>
      <body className="inline-block p-6 bg-gradient-to-bl from-green-400 to-blue-400">
        <main className={inter.className}>{children}</main>
      </body>
      
    </html>
  )
};
