import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import Navbar from '@/components/navbar'
import { Separator } from '@/components/ui/separator'
import { ThemeProvider } from "@/components/theme-provider"
import Footer from '@/components/footer'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ian Olmstead',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={raleway.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div  className="flex justify-end">
            <Navbar/>
          </div>

          <div>
            <Separator />
          </div>

          {children}

          <div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
